package com.minimarket.web.entity;
// Generated 29-10-2018 14:07:51 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca")
public class Marca implements java.io.Serializable {

	private Integer idMarca;
	private String nombreMarca;
	private String descripcionMarca;
	private Set<Producto> productos = new HashSet<Producto>(0);
	private Set<Producto> productos_1 = new HashSet<Producto>(0);
	private Set<Producto> productos_2 = new HashSet<Producto>(0);

	public Marca() {
	}

	public Marca(String nombreMarca, String descripcionMarca) {
		this.nombreMarca = nombreMarca;
		this.descripcionMarca = descripcionMarca;
	}

	public Marca(String nombreMarca, String descripcionMarca, Set<Producto> productos, Set<Producto> productos_1,
			Set<Producto> productos_2) {
		this.nombreMarca = nombreMarca;
		this.descripcionMarca = descripcionMarca;
		this.productos = productos;
		this.productos_1 = productos_1;
		this.productos_2 = productos_2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_marca", unique = true, nullable = false)
	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "nombre_marca", nullable = false, length = 50)
	public String getNombreMarca() {
		return this.nombreMarca;
	}

	public void setNombreMarca(String nombreMarca) {
		this.nombreMarca = nombreMarca;
	}

	@Column(name = "descripcion_marca", nullable = false, length = 100)
	public String getDescripcionMarca() {
		return this.descripcionMarca;
	}

	public void setDescripcionMarca(String descripcionMarca) {
		this.descripcionMarca = descripcionMarca;
	}

/*	@OneToMany(fetch = FetchType.EAGER, mappedBy = "marca")
	public Set<Producto> getProductos() {
		return this.productos;
	}*/

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	/*@OneToMany(fetch = FetchType.EAGER, mappedBy = "marca")
	public Set<Producto> getProductos_1() {
		return this.productos_1;
	}

	public void setProductos_1(Set<Producto> productos_1) {
		this.productos_1 = productos_1;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "marca")
	public Set<Producto> getProductos_2() {
		return this.productos_2;
	}

	public void setProductos_2(Set<Producto> productos_2) {
		this.productos_2 = productos_2;
	}*/

}
